version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew test
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - build/libs/*.jar
    - scripts/*.sh
    - appsepc.yml
  discard-paths: yes
